<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>Aspose.3D.FOSS</AssemblyName>
    <PackageId>Aspose.3D.FOSS</PackageId>
    <Version>26.1.0</Version>
    <Authors>Aspose</Authors>
    <Description>FOSS implementation of Aspose.3D for .NET</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/aspose-3d-foss/Aspose.3D-FOSS-for-.NET</RepositoryUrl>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <TargetFramework />
    <TargetFrameworks>net10.0;net8.0;net6.0;netcoreapp3.1</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup >
      <None Include="..\..\..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>
</Project>
