<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>Aspose.3D</AssemblyName>
    <PackageId>Aspose.3D</PackageId>
    <Version>26.1.0</Version>
    <Authors>Aspose</Authors>
    <Description>FOSS implementation of Aspose.3D for .NET</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/aspose-3d/Aspose.3D-for-.NET</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup />
</Project>
