using System;
using System.Collections.Generic;
using System.IO;
using Aspose.ThreeD.Entities;
using Aspose.ThreeD.Utilities;

namespace Aspose.ThreeD.Formats
{
    /// <summary>
    /// OBJ format writer
    /// </summary>
    internal class ObjWriter : IExporter
    {
        public void Export(Scene scene, Stream stream, SaveOptions options)
        {
            if (options is ObjSaveOptions objOptions)
            {
                Write(stream, scene, objOptions);
            }
            else
            {
                throw new ArgumentException("Options must be ObjSaveOptions", nameof(options));
            }
        }

        private static void Write(Stream stream, Scene scene, ObjSaveOptions options)
        {
            using (var writer = new StreamWriter(stream, leaveOpen: true))
            {
                Write(writer, scene, options);
            }
        }

        private static void Write(StreamWriter writer, Scene scene, ObjSaveOptions options)
        {
            if (options.Verbose)
            {
                writer.WriteLine("# Generated by Aspose.3D FOSS Implementation");
                writer.WriteLine($"# Export date: {DateTime.Now}");
            }

            WriteNodes(writer, scene.RootNode, options);
        }

        private static void WriteNodes(StreamWriter writer, Node node, ObjSaveOptions options)
        {
            var vertexOffset = 1;

            foreach (var entity in node.Entities)
            {
                if (entity is Mesh entityMesh)
                {
                    WriteMesh(writer, entityMesh, vertexOffset, options);
                    vertexOffset += entityMesh.ControlPoints.Count;
                }
                else if (entity is Primitive primitive)
                {
                    var primitiveMesh = primitive.ToMesh();
                    WriteMesh(writer, primitiveMesh, vertexOffset, options);
                    vertexOffset += primitiveMesh.ControlPoints.Count;
                }
            }

            foreach (var childNode in node.ChildNodes)
            {
                WriteNodes(writer, childNode, options);
            }
        }

        private static void WriteMesh(StreamWriter writer, Mesh mesh, int vertexOffset, ObjSaveOptions options)
        {
            if (options.Verbose)
            {
                writer.WriteLine($"# Object: {mesh.Name}");
                writer.WriteLine($"# Vertices: {mesh.ControlPoints.Count}");
                writer.WriteLine($"# Polygons: {mesh.PolygonCount}");
            }

            if (mesh.Name != null && mesh.Name != "Mesh")
            {
                writer.WriteLine($"o {mesh.Name}");
            }

            foreach (var vertex in mesh.ControlPoints)
            {
                var x = vertex.X;
                var y = vertex.Y;
                var z = vertex.Z;
                var w = options.SerializeW ? vertex.W : 1.0f;

                if (options.FlipCoordinateSystem)
                {
                    y = -y;
                }

                writer.WriteLine($"v {x} {y} {z} {w}");
            }

            foreach (var polygon in mesh.Polygons)
            {
                if (polygon.Length == 3)
                {
                    writer.WriteLine($"f {polygon[0] + vertexOffset} {polygon[1] + vertexOffset} {polygon[2] + vertexOffset}");
                }
                else if (polygon.Length == 4)
                {
                    writer.WriteLine($"f {polygon[0] + vertexOffset} {polygon[1] + vertexOffset} {polygon[2] + vertexOffset} {polygon[3] + vertexOffset}");
                }
                else
                {
                    var indices = new List<string>();
                    foreach (var idx in polygon)
                    {
                        indices.Add((idx + vertexOffset).ToString());
                    }
                    writer.WriteLine($"f {string.Join(" ", indices)}");
                }
            }
        }
    }
}
