using System;
using Aspose.ThreeD.Render;
using Aspose.ThreeD.Utilities;

namespace Aspose.ThreeD.Entities
{
    /// <summary>
    /// Parameterized rectangular torus.
    /// </summary>
    public class RectangularTorus : Primitive, INamedObject, IMeshConvertible
    {
        private double _innerRadius;
        private double _outerRadius;
        private double _height;
        private double _arc;
        private double _angleStart;
        private int _radialSegments;

        /// <summary>
        /// Constructor of RectangularTorus
        /// </summary>
        public RectangularTorus() : this("RectangularTorus")
        {
        }

        /// <summary>
        /// Constructor of RectangularTorus
        /// </summary>
        /// <param name="name">Entity name</param>
        public RectangularTorus(string name) : base(name)
        {
            _innerRadius = 17;
            _outerRadius = 20;
            _height = 20;
            _arc = Math.PI;
            _angleStart = 0;
            _radialSegments = 10;
        }

        /// <summary>
        /// The inner radius of the rectangular torus. Default value is 17
        /// </summary>
        public double InnerRadius
        {
            get => _innerRadius;
            set => _innerRadius = value;
        }

        /// <summary>
        /// The outer radius of the rectangular torus. Default value is 20
        /// </summary>
        public double OuterRadius
        {
            get => _outerRadius;
            set => _outerRadius = value;
        }

        /// <summary>
        /// The height of the rectangular torus. Default value is 20
        /// </summary>
        public double Height
        {
            get => _height;
            set => _height = value;
        }

        /// <summary>
        /// The total angle of the arc, measured in radian. Default value is PI
        /// </summary>
        public double Arc
        {
            get => _arc;
            set => _arc = value;
        }

        /// <summary>
        /// The start angle of the arc, measured in radian. Default value is 0
        /// </summary>
        public double AngleStart
        {
            get => _angleStart;
            set => _angleStart = value;
        }

        /// <summary>
        /// The radial segments, default value is 10
        /// </summary>
        public int RadialSegments
        {
            get => _radialSegments;
            set => _radialSegments = value;
        }

        /// <summary>
        /// Convert this primitive to mesh
        /// </summary>
        public override Mesh ToMesh()
        {
            var mesh = new Mesh(Name);
            var innerRadius = (float)_innerRadius;
            var outerRadius = (float)_outerRadius;
            var height = (float)_height;
            var arc = (float)_arc;
            var angleStart = (float)_angleStart;

            // Generate vertices for the rectangular torus
            // The rectangular torus is a ring-shaped object with rectangular cross-section
            // It's generated by sweeping a rectangle around an arc

            for (int i = 0; i <= _radialSegments; i++)
            {
                var angle = angleStart + (double)i / _radialSegments * arc;
                var cosAngle = Math.Cos(angle);
                var sinAngle = Math.Sin(angle);

                // Generate the rectangle cross-section at each radial segment
                // The rectangle has outer radius and inner radius edges

                // Bottom-left corner (inner radius, -height/2)
                var x1 = (float)(_innerRadius * cosAngle);
                var y1 = (float)(_innerRadius * sinAngle);
                var z1 = -(float)_height / 2;
                mesh.ControlPoints.Add(new Vector4(x1, y1, z1, 1));

                // Bottom-right corner (outer radius, -height/2)
                var x2 = (float)(_outerRadius * cosAngle);
                var y2 = (float)(_outerRadius * sinAngle);
                var z2 = -(float)_height / 2;
                mesh.ControlPoints.Add(new Vector4(x2, y2, z2, 1));

                // Top-right corner (outer radius, height/2)
                var x3 = (float)(_outerRadius * cosAngle);
                var y3 = (float)(_outerRadius * sinAngle);
                var z3 = (float)_height / 2;
                mesh.ControlPoints.Add(new Vector4(x3, y3, z3, 1));

                // Top-left corner (inner radius, height/2)
                var x4 = (float)(_innerRadius * cosAngle);
                var y4 = (float)(_innerRadius * sinAngle);
                var z4 = (float)_height / 2;
                mesh.ControlPoints.Add(new Vector4(x4, y4, z4, 1));
            }

            // Create polygons connecting adjacent vertices
            // Each segment has 4 vertices, and we connect them with quads
            for (int i = 0; i < _radialSegments; i++)
            {
                var baseIdx = i * 4;

                // Connect the four sides of the rectangular ring
                // Side 1: inner face (connecting inner radius vertices)
                mesh.CreatePolygon(baseIdx + 0, baseIdx + 4, baseIdx + 5, baseIdx + 1);
                // Side 2: bottom face
                mesh.CreatePolygon(baseIdx + 1, baseIdx + 5, baseIdx + 6, baseIdx + 2);
                // Side 3: outer face (connecting outer radius vertices)
                mesh.CreatePolygon(baseIdx + 2, baseIdx + 6, baseIdx + 7, baseIdx + 3);
                // Side 4: top face
                mesh.CreatePolygon(baseIdx + 3, baseIdx + 7, baseIdx + 4, baseIdx + 0);
            }

            // Close the ring by connecting the last segment to the first
            if (_radialSegments > 0)
            {
                var lastBase = (_radialSegments - 1) * 4;
                var firstBase = 0;

                // Connect last to first
                mesh.CreatePolygon(lastBase + 0, firstBase + 4, firstBase + 5, lastBase + 1);
                mesh.CreatePolygon(lastBase + 1, firstBase + 5, firstBase + 6, lastBase + 2);
                mesh.CreatePolygon(lastBase + 2, firstBase + 6, firstBase + 7, lastBase + 3);
                mesh.CreatePolygon(lastBase + 3, firstBase + 7, firstBase + 4, lastBase + 0);
            }

            return mesh;
        }

    }
}
