using System;
using Aspose.ThreeD.Render;
using Aspose.ThreeD.Utilities;

namespace Aspose.ThreeD.Entities
{
    /// <summary>
    /// Parameterized torus.
    /// </summary>
    public class Torus : Primitive, INamedObject, IMeshConvertible
    {
        private double _radius;
        private double _tube;
        private int _radialSegments;
        private int _tubularSegments;
        private double _arc;

        /// <summary>
        /// Initializes a new instance of the Torus class.
        /// </summary>
        public Torus() : this(1, 0.25, Math.PI * 2)
        {
        }

        /// <summary>
        /// Initializes a new instance of the Torus class.
        /// </summary>
        /// <param name="radius">Radius of the torus</param>
        /// <param name="tube">Radius of the tube</param>
        public Torus(double radius, double tube) : this(radius, tube, Math.PI * 2)
        {
        }

        /// <summary>
        /// Initializes a new instance of the Torus class.
        /// </summary>
        /// <param name="radius">Radius of the torus</param>
        /// <param name="tube">Radius of the tube</param>
        /// <param name="arc">Arc angle</param>
        public Torus(double radius, double tube, double arc) : this("Torus", radius, tube, 32, 16, arc)
        {
        }

        /// <summary>
        /// Initializes a new instance of the Torus class.
        /// </summary>
        /// <param name="name">Name of the torus</param>
        /// <param name="radius">Radius of the torus</param>
        /// <param name="tube">Radius of the tube</param>
        /// <param name="radialSegments">Radial segments</param>
        /// <param name="tubularSegments">Tubular segments</param>
        /// <param name="arc">Arc angle</param>
        public Torus(string name, double radius, double tube, int radialSegments, int tubularSegments, double arc) : base(name)
        {
            _radius = radius;
            _tube = tube;
            _radialSegments = radialSegments;
            _tubularSegments = tubularSegments;
            _arc = arc;
        }

        /// <summary>
        /// Gets or sets the radius of the torus.
        /// </summary>
        public double Radius
        {
            get => _radius;
            set => _radius = value;
        }

        /// <summary>
        /// Gets or sets the radius of the tube.
        /// </summary>
        public double Tube
        {
            get => _tube;
            set => _tube = value;
        }

        /// <summary>
        /// Gets or sets the radial segments.
        /// </summary>
        public int RadialSegments
        {
            get => _radialSegments;
            set => _radialSegments = value;
        }

        /// <summary>
        /// Gets or sets the tubular segments.
        /// </summary>
        public int TubularSegments
        {
            get => _tubularSegments;
            set => _tubularSegments = value;
        }

        /// <summary>
        /// Gets or sets the arc.
        /// </summary>
        public double Arc
        {
            get => _arc;
            set => _arc = value;
        }

        /// <summary>
        /// Convert current object to mesh
        /// </summary>
        public override Mesh ToMesh()
        {
            var mesh = new Mesh(Name);
            var radius = (float)_radius;
            var tube = (float)_tube;
            var arc = (float)_arc;

            // Generate vertices for the torus
            // The torus is generated by sweeping a circle (tube) around an axis
            // u parameter: angle around the main circle (0 to arc)
            // v parameter: angle around the tube circle (0 to 2*PI)

            for (int i = 0; i <= _radialSegments; i++)
            {
                var u = (double)i / _radialSegments * arc;
                var cosU = Math.Cos(u);
                var sinU = Math.Sin(u);

                for (int j = 0; j <= _tubularSegments; j++)
                {
                    var v = (double)j / _tubularSegments * Math.PI * 2;
                    var cosV = Math.Cos(v);
                    var sinV = Math.Sin(v);

                    // Torus parametric equation:
                    // x = (R + r*cos(v)) * cos(u)
                    // y = (R + r*cos(v)) * sin(u)
                    // z = r * sin(v)
                    var x = (float)((_radius + _tube * cosV) * cosU);
                    var y = (float)((_radius + _tube * cosV) * sinU);
                    var z = (float)(_tube * sinV);

                    mesh.ControlPoints.Add(new Vector4(x, y, z, 1));
                }
            }

            // Create polygons connecting adjacent vertices
            for (int i = 0; i < _radialSegments; i++)
            {
                for (int j = 0; j < _tubularSegments; j++)
                {
                    var first = i * (_tubularSegments + 1) + j;
                    var second = first + _tubularSegments + 1;

                    mesh.CreatePolygon(first, first + 1, second + 1, second);
                }
            }
             return mesh;
        }
    }
}